// import 'core-js/stable';
export { default as anime } from 'animejs/lib/anime.es.js';
export { Utilities } from './lib/Utilities';
export { AdjustSize } from './lib/AdjustSize';
export { PopupAdjust } from './lib/PopupAdjust';
export { FlowVox } from './lib/FlowVox';
export { FadeSlider } from './lib/FadeSlider';
export { SimpleSlider } from './lib/SimpleSlider';
export { ReplaceImageSP } from './lib/ReplaceImageSP';
export { RSSFeed } from './lib/RSSFeed';
export { InstaFeed } from './lib/InstaFeed';

// import anime from 'animejs/lib/anime.es.js';
// import Utilities from './lib/Utilities';
// import AdjustSize from './lib/AdjustSize';
// import PopupAdjust from './lib/PopupAdjust';
// import FlowVox from './lib/FlowVox';
// import FadeSlider from './lib/FadeSlider';
// import ReplaceImageSP from './lib/ReplaceImageSP';
// import RSSFeed from './lib/RSSFeed';
// import InstaFeed from './lib/InstaFeed';
