// import 'core-js/stable';
export { default as anime } from 'animejs/lib/anime.es.js';
export { Utilities } from './lib/Utilities';
export { AdjustSize } from './lib/AdjustSize';
export { PopupAdjust } from './lib/PopupAdjust';
export { FlowVox } from './lib/FlowVox';
export { FadeSlider } from './lib/FadeSlider';
export { FocusLoop } from './lib/FocusLoop';
export { SimpleSlider } from './lib/SimpleSlider';
export { SimpleAccordion } from './lib/SimpleAccordion';
export { SimpleTab } from './lib/SimpleTab';
export { SimpleCookie } from './lib/SimpleCookie';
export { RatioAdjust } from './lib/RatioAdjust';
export { ReplaceImageSP } from './lib/ReplaceImageSP';
export { LazyLoadBg } from './lib/LazyLoadBg';
export { RSSFeed } from './lib/RSSFeed';
export { InstaFeed } from './lib/InstaFeed';
